on: [push, pull_request]

name: check

jobs:
  check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NOT_CRAN: true
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          extra-repositories: 'https://mc-stan.org/r-packages/'
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::cmdstanr
            any::rmarkdown
            any::knitr
            local::.
          needs: check
          cache-version: 2

      - name: Cache CmdStan build
        uses: actions/cache@v3
        with:
          path: ~/.cmdstan
          key: ${{ runner.os }}-cmdstan-2

      - name: Install CmdStan
        shell: Rscript {0}
        run: |
          cmdstanr::check_cmdstan_toolchain(fix = TRUE)

          # Set CmdStan path explicitly (in case it was restored from cache)
          cmdstan_dir <- fs::dir_ls("~/.cmdstan", type = "directory", recurse = FALSE)[1]
          cmdstanr::set_cmdstan_path(cmdstan_dir)

          # Install CmdStan only if not already installed
          if (!cmdstanr::cmdstan_version() > "0.0.0") {
            cmdstanr::install_cmdstan()
          }

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
