name: Render Vignettes

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  render-vignettes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev pandoc texlive texlive-xetex texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            quarto
            rmarkdown

      - name: Render HTML and PDF vignettes
        run: |
          quarto render vignettes/Introduction.qmd --to html
          quarto render vignettes/Introduction.qmd --to pdf

      - name: Upload rendered vignettes as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-vignettes
          path: |
            vignettes/Introduction.html
            vignettes/Introduction.pdf